# Generated by Django 4.1 on 2022-08-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaces_available', models.PositiveBigIntegerField()),
                ('email_with_payment_information', models.TextField(blank=True, default='')),
                ('email_when_in_waiting_list', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=9000)),
                ('email', models.EmailField(max_length=254)),
                ('signup_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Waiting Payment'), ('confirmed', 'Payment confirmed'), ('waiting_list', 'Waiting list')], max_length=50)),
            ],
        ),
    ]
