# Generated by Django 4.1 on 2022-08-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaces_available', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=9000)),
                ('email', models.EmailField(max_length=254)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('signup_date', models.DateTimeField()),
            ],
        ),
    ]
